name: community_health
version: 1.0.0+1
publish_to: "none"

description: Giao diện demo sổ tay tiêm chủng ngoại tuyến và giám sát dịch tễ vùng sâu.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.3
  workmanager: ^0.5.2
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^3.5.7
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
