name: community_health
version: 1.0.0+1
publish_to: "none"

description: Giao diện demo sổ tay tiêm chủng ngoại tuyến và giám sát dịch tễ vùng sâu.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.7
  sqflite: ^2.3.0
  path: ^1.9.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^7.2.0
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.3
  workmanager: ">=0.5.2 <1.0.0"
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.2.3
  fl_chart: ^0.68.0
  # Export Excel / PDF
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
