name: community_health
version: 1.0.0+1
publish_to: "none"

description: Giao diện demo sổ tay tiêm chủng ngoại tuyến và giám sát dịch tễ vùng sâu.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
